<script lang="ts">
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';

  let mounted = false;

  const blogPosts = [
    {
      title: 'Building Xavier2: A Memory Core for AI Agents',
      excerpt: 'How I built a persistent memory system in Rust with vector search and knowledge graphs.',
      date: 'Coming Soon',
      tags: ['Rust', 'AI', 'Systems'],
      draft: true,
    },
    {
      title: 'Multi-Agent Orchestration with Gestalt',
      excerpt: 'Designing a CLI orchestrator that coordinates multiple AI agents using SurrealDB.',
      date: 'Coming Soon',
      tags: ['Rust', 'Agents', 'Architecture'],
      draft: true,
    },
    {
      title: 'Offline-First Architecture for Mobile',
      excerpt: 'Patterns and trade-offs for building resilient mobile apps with Flutter.',
      date: 'Coming Soon',
      tags: ['Flutter', 'Mobile', 'Architecture'],
      draft: true,
    },
  ];

  onMount(() => {
    mounted = true;
  });
</script>

<section id="blog" class="relative py-32 px-6">
  <div class="max-w-6xl mx-auto">
    {#if mounted}
      <div in:fly={{ y: 40, duration: 800, easing: quintOut }}>
        <span class="text-neon-green font-mono text-sm tracking-widest mb-4 block"># blog</span>
        <h2 class="section-title">
          Insights & <span class="text-gradient">architecture</span>
        </h2>
        <p class="text-gray-500 text-lg mt-4 max-w-2xl">
          Deep dives into systems architecture, AI infrastructure, and the engineering behind my projects.
          <span class="text-neon-green/60"> Blog posts are being generated via my automated pipeline.</span>
        </p>
      </div>
    {/if}

    <div class="grid md:grid-cols-3 gap-6 mt-12">
      {#each blogPosts as post, i (post.title)}
        <div
          class="glass-card p-6 hover:neon-glow-blue transition-all duration-500 group {post.draft ? 'opacity-60' : ''}"
          in:fly={{ y: 30, duration: 600, delay: i * 150, easing: quintOut }}
        >
          {#if post.draft}
            <div class="flex items-center gap-2 mb-3">
              <span class="px-2 py-0.5 rounded text-xs font-mono bg-yellow-500/10 text-yellow-400 border border-yellow-400/20">
                Draft
              </span>
              <span class="text-xs text-gray-600 font-mono">{post.date}</span>
            </div>
          {:else}
            <span class="text-xs text-gray-500 font-mono">{post.date}</span>
          {/if}

          <h3 class="text-lg font-semibold mt-2 mb-3 text-white group-hover:text-neon-green transition-colors">
            {post.title}
          </h3>
          <p class="text-sm text-gray-500 leading-relaxed mb-4">
            {post.excerpt}
          </p>

          <div class="flex flex-wrap gap-2">
            {#each post.tags as tag}
              <span class="tech-badge text-xs">{tag}</span>
            {/each}
          </div>
        </div>
      {/each}
    </div>

    <div class="text-center mt-10">
      <p class="text-gray-600 text-sm font-mono">
        Autogenerated blog posts via SWAL pipeline · Posts coming as projects mature
      </p>
    </div>
  </div>
</section>
